name: LineageOS_Kernel_CI-giulia

on:
  workflow_dispatch:

jobs:
  LineageOS_Kernel_CI:
    name: LineageOS Kernel CI
    runs-on: self-hosted
    steps:

    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 1

    - name: Clone Kernel and Dependencies
      run: |
        git clone https://github.com/oplus-giulia-dev/android_kernel_oneplus_sm8650.git --depth=1 -b lineage-23.0 kernel/oneplus/sm8650
        git clone https://github.com/oplus-giulia-dev/android_kernel_oneplus_sm8650-modules.git --depth=1 -b lineage-23.0 kernel/oneplus/sm8650-modules
    
    - name: Setup release name
      run: |
        rm -rf ${GITHUB_WORKSPACE}/*.zip
        cd kernel/oneplus/sm8650
        SUBLEVEL=$(grep "^SUBLEVEL =" Makefile | awk '{print $3}')
        REL_NAME="LineageOS_OPSM8650-v6.1.${SUBLEVEL}-$(date +"%Y%m%d")"
        echo "REL_NAME=${REL_NAME}" >> $GITHUB_ENV

    - name: Build Kernel with ksu
      run: |
        cd kernel/oneplus/sm8650
        build_sm8650 --clean --ksu
        mv kernel.zip ${GITHUB_WORKSPACE}/ksu.zip
        git clean -fdx && find . -mindepth 1 -maxdepth 1 -type d -exec test -d "{}/.git" \; -print | xargs rm -rf && git reset --hard
        cd -

    - name: Build Kernel with ksu-next
      run: |
        cd kernel/oneplus/sm8650
        build_sm8650 --clean --ksu-next
        mv kernel.zip ${GITHUB_WORKSPACE}/ksu-next.zip
        git clean -fdx && find . -mindepth 1 -maxdepth 1 -type d -exec test -d "{}/.git" \; -print | xargs rm -rf && git reset --hard
        cd -

    - name: Build Kernel with ksu-next + susfs
      run: |
        cd kernel/oneplus/sm8650
        build_sm8650 --clean --ksu-next-susfs
        mv kernel.zip ${GITHUB_WORKSPACE}/ksu-next-susfs.zip
        git clean -fdx && find . -mindepth 1 -maxdepth 1 -type d -exec test -d "{}/.git" \; -print | xargs rm -rf && git reset --hard
        cd -

    - name: Create GitHub Release
      run: |
        cd ${GITHUB_WORKSPACE}
        gh release create "$REL_NAME" --title "$REL_NAME" --notes "" ksu.zip ksu-next.zip ksu-next-susfs.zip
